### ISSUE TITLE
this works on hassio?

### ISSUE THREAD

**Issue by delorean-dev** [araa47/hass_bletracker#1]
hello buddy , this work on hassio?

**Comment by araa47** [comment]
I can't seem to figure out how to get this on hassio since I need to install some extra components and require sudo bluetooth access. You could, however, install this on a raspberry pi zero and use that as the Bluetooth tracker component.  You would just need to point your homeassistant to the pi zero's ip address in the configuration.yaml file.

**Comment by delorean-dev** [comment]
ok thank you, i will test it .

**Comment by araa47** [comment]
Great, let me know if you have any issues, will close this for now, and add this information in the README.md file.
